Server:
  HTTP:
    Host: "0.0.0.0"
    Port: 8111
Service:
  Dao:
    Redis:
      Address: "127.0.0.1"
      Port: 6379
      Password: "tQF08UDhtu6g5VjghhYmag=="
      Database: 0
  OssClientConfig:
    Local:
      BucketService:
        Host: "0.0.0.0"
        Port: 9001
