Server:
  HTTP:
    Host: "0.0.0.0"
    Port: 8111
Service:
  OssClientConfig:
    Local:
      AccessKey: "18888888888"
      AccessSecret: "18888888888"
      BucketName: "temp"
      BucketServiceUrl : "http://192.168.10.101:9100/libong/manager/api/oss/upload"
