Server:
  HTTP:
    Host: "0.0.0.0"
    Port: 8111
Service:
  OssClientConfig:
    AccessKeyID: "18888888881"
    AccessKeySecret: "18888888881"
    Bucket: "no_change"
    BucketServiceUrl : "http://172.20.10.196:9100/manager/api/libong/ossupload"
