# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: 
      - dev-test
  pull_request:
    branches: 
      - main

jobs:
#定义工作流名称
  build:
    #运行任务的虚拟环境
    runs-on: ubuntu-latest
    #运行任务的最大分钟数
    timeout-minutes: 3
    #步骤
    steps:
    - name: Check out Go
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

      #设置环境变量 适用于私有库的依赖访问
    - name: make env
      shell: bash
      run: |
        export GO111MODULE=on
        export GOPRIVATE=github.com/Libong
        export GOPROXY=https://goproxy.cn,direct
        git config --global url."https://libong:${{secrets.GO_MOD}}@github.com".insteadOf "https://github.com"
      #下载依赖
    - name: Install dependencies
      run:  go mod tidy
      #编译
    - name: build
      run : go build ./app/interface/oss/cmd/main.go
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: oss
        path: /home/runner/work/oss/oss
    - name: Login to ali cloud
      uses: aliyun/acr-login@v1
      with:
        login-server: registry.cn-hangzhou.aliyuncs.com
        region-id: cn-hangzhou
        username: ${{ secrets.ALIBABA_CLOUD_USERNAME }}
        password: ${{ secrets.ALIBABA_CLOUD_PASSWORD }}
    - name: Build and push docker image
      env:
        IMAGE_TAG: ${{github.sha}}
      run: |
        docker build -t registry.cn-hangzhou.aliyuncs.com/libong/test-rep:$IMAGE_TAG .
        docker push registry.cn-hangzhou.aliyuncs.com/libong/test-rep:$IMAGE_TAG
#      uses: alibaba/acr-login-action@v1
#      with:
#        registry: registry.cn-hangzhou.aliyuncs.com/libong/test-rep
#        username: ${{ secrets.ALIBABA_CLOUD_USERNAME }}
#        password: ${{ secrets.ALIBABA_CLOUD_PASSWORD }}
#    - name: Containerize Application
#      uses: docker/build-push-action@v2
#      with:
#        push: true
#        tags: your-alibaba-cloud-registry.com/your-repo/myapp:latest
#        build: |
#          docker build -t myapp .
#    - name: Deploy to Alibaba Cloud Container Registry
#      env:
#        REGISTRY: your-alibaba-cloud-registry.com
#        IMAGE: your-repo/myapp:latest
#      run: |
#        docker tag myapp $REGISTRY/$IMAGE
#        docker push $REGISTRY/$IMAGE

