# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: 
      - dev-test
  pull_request:
    branches: 
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Check out Go
      run: actions/checkout@v3

    - name: make env
      shell: bash
      run: |
        export GO111MODULE=on
        export GOPRIVATE=github.com/Libong
        export GOPROXY=https://goproxy.cn,direct
        git config --global --add url."git@github.com:".insteadOf "https://github.com/" 
        make ci
    - name: Install dependencies
      run:  go mod tidy
    - name: build
      run : go build
